apiVersion: networking.k8s.io/v1 # Phiên bản API cho Ingress, ở đây sử dụng phiên bản networking.k8s.io/v1.

# Ingress dùng để quản lý và định tuyến lưu lượng HTTP/HTTPS từ bên ngoài vào các dịch vụ bên trong Kubernetes.
kind: Ingress # Xác định loại tài nguyên
metadata:
  name: trustpay-be # Tên của Ingress này là trustpay-be
spec:
  # Định cấu hình TLS (giao thức mã hóa HTTPS) cho các tên miền được liệt kê
  tls:
    # Ingress sẽ yêu cầu chứng chỉ TLS cho các tên miền này để bảo vệ lưu lượng HTTPS.
    - hosts:
        - api-uat.bitback.community
        - admin-api-uat.bitback.community
        - partner-api-uat.bitback.community
  rules:
    # rule 1
    - host: api-uat.bitback.community # Nếu yêu cầu đến api-uat.bitback.community
      http:
        paths:
          - pathType: Prefix
            # Định tuyến toàn bộ các request (path: '/') đến service: trustpay-be-gateway
            path: '/'
            backend:
              service:
                # Gửi yêu cầu đến dịch vụ trustpay-be-gateway.
                name: trustpay-be-gateway
                # Sử dụng cổng HTTP của service (được định nghĩa trong file Service trustpay-be-gateway).
                port: { name: http }

    # rule 2
    - host: admin-api-uat.bitback.community
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: trustpay-be-cms
                port: { name: http }

    # rule 3
    - host: partner-api-uat.bitback.community
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: trustpay-be-thirdparty
                port: { name: http }
