export enum QUEUES {
  AUTHENTICATOR = 'AUTHENTICATOR_QUEUE',
  CASHBACK = 'CASHBACK_QUEUE',
  MINIGAME = 'MINIGAME_QUEUE',
  BITFARM = 'BITFARM_QUEUE',
  WALLET = 'WALLET_QUEUE',
  BITLOT = 'BITLOT_QUEUE',
}
